//Selected Category Ids: 8, 54, 82, 120, 40, 47, 51
//[].slice.call(document.getElementsByName('categoryIds[]')).map((f,i) => {return "{ id:"+i + ", categorytext: '"+ f.labels[0].innerText.replace(/\n/,'').replace(/\[.*\]/,'')+"' , code : '"+ f.value +"'},";}).join('\n');
export const categoryMap = [
{ id:0, categorytext: 'Ausstellungen' , code : '115'},
{ id:1, categorytext: 'Dauerausstellungen' , code : '114'},
{ id:2, categorytext: 'Führungen' , code : '116'},
{ id:3, categorytext: 'Vernissagen' , code : '113'},
{ id:4, categorytext: 'Weiterbildungen' , code : '90'},
{ id:5, categorytext: 'Weitere Bildungsangebote' , code : '91'},
{ id:6, categorytext: 'Comedy' , code : '10'},
{ id:7, categorytext: 'Kabarett' , code : '103'},
{ id:8, categorytext: 'Lesungen' , code : '8'},
{ id:9, categorytext: 'Oper & Operette' , code : '6'},
{ id:10, categorytext: 'Theater' , code : '3'},
{ id:11, categorytext: 'Weitere Bühnenkunst' , code : '9'},
{ id:12, categorytext: 'Begegnungsangebote' , code : '131'},
{ id:13, categorytext: 'Information & Beratung' , code : '111'},
{ id:14, categorytext: 'Sitzungen' , code : '110'},
{ id:15, categorytext: 'Soziale Dienste & Angebote' , code : '109'},
{ id:16, categorytext: 'Weitere Bürgerangebote' , code : '112'},
{ id:17, categorytext: 'Exkursionen & Wanderungen' , code : '92'},
{ id:18, categorytext: 'Feste' , code : '107'},
{ id:19, categorytext: 'Festivals' , code : '13'},
{ id:20, categorytext: 'Jahrmärkte' , code : '15'},
{ id:21, categorytext: 'Film, Kino, TV' , code : '18'},
{ id:22, categorytext: 'Kongresse, Konferenzen & Tagungen' , code : '54'},
{ id:23, categorytext: 'Country & Folk' , code : '94'},
{ id:24, categorytext: 'Elektro' , code : '21'},
{ id:25, categorytext: 'Gospel & Chöre' , code : '105'},
{ id:26, categorytext: 'HipHop, RnB, Soul & Funk' , code : '20'},
{ id:27, categorytext: 'Indie & Alternative' , code : '93'},
{ id:28, categorytext: 'Jazz, Blues, Swing & Chanson' , code : '22'},
{ id:29, categorytext: 'Klassik' , code : '82'},
{ id:30, categorytext: 'Pop' , code : '55'},
{ id:31, categorytext: 'Punkrock, Metal & Hardcore' , code : '106'},
{ id:32, categorytext: 'Reggae, Dancehall & Ska' , code : '102'},
{ id:33, categorytext: 'Rock' , code : '23'},
{ id:34, categorytext: 'Schlager & Volksmusik' , code : '24'},
{ id:35, categorytext: 'Singer/Songwriter' , code : '120'},
{ id:36, categorytext: 'Weltmusik' , code : '98'},
{ id:37, categorytext: 'Weitere Konzerte' , code : '25'},
{ id:38, categorytext: 'Musicals' , code : '29'},
{ id:39, categorytext: 'Shows & Varieté' , code : '30'},
{ id:40, categorytext: 'Weitere Musicals & Shows' , code : '32'},
{ id:41, categorytext: 'Flohmärkte' , code : '16'},
{ id:42, categorytext: 'Wochenmärkte' , code : '57'},
{ id:43, categorytext: 'Party' , code : '33'},
{ id:44, categorytext: 'Religion und Spiritualität' , code : '40'},
{ id:45, categorytext: 'Hafenrundfahrten' , code : '44'},
{ id:46, categorytext: 'Stadtrundfahrten' , code : '42'},
{ id:47, categorytext: 'Stadtrundgänge & Führungen' , code : '49'},
{ id:48, categorytext: 'Weitere Rundgänge & Fahrten' , code : '46'},
{ id:49, categorytext: 'Seminare, Kurse und Workshops' , code : '47'},
{ id:50, categorytext: 'Fitness' , code : '127'},
{ id:51, categorytext: 'Fußball' , code : '64'},
{ id:52, categorytext: 'Radtouren' , code : '36'},
{ id:53, categorytext: 'Tanzen' , code : '128'},
{ id:54, categorytext: 'Volleyball' , code : '126'},
{ id:55, categorytext: 'Yoga' , code : '118'},
{ id:56, categorytext: 'Weitere Sport & Bewegung' , code : '78'},
{ id:57, categorytext: 'Vorträge und Diskussionsrunden' , code : '51'},
{ id:58, categorytext: 'Sonstige' , code : '52'},
];
